import { Project } from "./types";

export const projects: Project[] = [
  {
    id: "3",
    title: "摄影出游季",
    subtitle: "TRAVEL PHOTO SEASON",
    description:
      "借助假期出游热度，转转为迎接用户旅行拍照需求，针对拍照类手机推出了丰厚的优惠券。旨在提升GMV规模，助力手机达成订单目标",
    coverImage: "/images/travel-photo-season.jpg",
    imageUrl: "/images/travel-photo-season.jpg",
    category: "landing",
    year: 2024,
    tags: ["大促设计", "视觉落地", "摄影出行"],
    designBy: "王军震",
    themeColor: "#ff4d4f",
    layout: "cyber",
    strategy: [
      "使用出行工具为背景氛围，增强页面的旅游出行感受",
      "颜色采用符合季节的主色调",
      "利用AI生成摄影类素材图来解决没有对应素材图的痛点",
    ],
    secondaryImages: [
      "/images/travel-photo-season.jpg",
      "/images/practice-moodboard.jpg",
      "/images/practice-autumn-illustration.jpg",
      "/images/practice-winter-render.jpg",
      "/images/practice-camera-board.jpg",
    ],
  },
  {
    id: "8",
    title: "羊角角IP设计",
    subtitle: "SHEEP CORNER IP DESIGN",
    description:
      "羊角角表面是个总犯困的小羊， 实际上是专门执行夜间秘密行动的成员。 喜欢足球、夜跑、滑板 and 深夜一个人待着。 有时候会在早上收到神秘消息： 没人知道羊角角真正的任务是什么。 只知道每当夜晚降临， 它就会消失在城市里。🌙它会穿过没人的小巷、便利店门口、凌晨的天桥。专门接那些奇怪的任务：回收被丢掉的梦想、寻找失踪的快乐、或者偷偷暗杀掉人类今天的坏情绪。",
    coverImage: "/images/sheep-corner-ip.png",
    imageUrl: "/images/sheep-corner-ip.png",
    category: "personal",
    year: 2025,
    tags: ["3D建模", "角色设计", "插图"],
    designBy: "王军震",
    themeColor: "#4A90E2",
    layout: "dynamic",
    secondaryImages: [
      "/images/sheep-corner-ip.png",
      "/images/sheep-sketch.png",
      "/images/sheep-model.png",
      "/images/sheep-paint.png",
      "/images/sheep-sketch.png",
      "/images/sheep-lineup.png",
      "/images/sheep-story-video.mp4",
    ],
  },
  {
    id: "9",
    title: "氢弹大促・新春年货节",
    subtitle: "SPRING FESTIVAL CARNIVAL",
    description:
      "项目背景：\n借力春节年货消费热潮打造「氢弹大促」营销活动，针对新客、老客、高粘性核心用户等不同圈层人群，定制分层差异化福利与优惠玩法，精准撬动不同用户消费潜力，最大化活动转化。",
    coverImage: "/images/spring-festival-carnival.jpg",
    imageUrl: "/images/spring-festival-carnival.jpg",
    category: "landing",
    year: 2025,
    tags: ["大促设计", "新春年味", "视觉落地", "趣味抢购"],
    designBy: "王军震",
    themeColor: "#e11d48",
    layout: "cyber",
    strategy: [
      "强化浓厚新春年味，清晰展示活动商品与优惠亮点",
      "打造趣味互动视觉，烘托热闹抢购氛围，加深用户记忆点",
      "结合 AI 设计工具全流程提效，快速产出多版本视觉物料",
      "深度融合春节传统视觉符号，还原居家过年场景，氛围感拉满",
      "以「商品破屏」和群体互动创造戏剧感，视觉生动吸睛",
      "主次分明展示年货商品，直观传递大促力度",
    ],
    secondaryImages: [
      "/images/spring-festival-carnival.jpg",
      "/images/spring-festival-secondary3.jpg",
      "/images/spring-festival-secondary1.jpg",
      "/images/spring-festival-secondary2.jpg",
      "/images/input-file-11.mp4",
      "/images/618-secondary1.jpg",
      "/images/618-secondary2.jpg",
      "/images/practice-winter-render.jpg",
      "/images/practice-autumn-illustration.jpg",
      "/images/practice-camera-board.jpg",
      "/images/practice-moodboard.jpg",
    ],
  },
  {
    id: "10",
    title: "开春出行季",
    subtitle: "SPRING TRAVEL CAMPAIGN",
    description: "春日融融，暖风拂面，户外旅行与踏春拍照热度飙升。转转平台顺应潮流推出「开春出行季」营销专区活动，主打精选运动穿戴与手持摄影神器日租福利。项目视觉落地围绕“春日出游，一拍封神”的核心概念，将潮流大疆 Pocket 3 及高端配件置于自然年轮木墩上，完美契合开春清新鲜活的主色调。旨在直击出游核心转化点，通过视觉冲击力实现品类租售转化的全新突破。",
    coverImage: "/images/spring-travel-campaign.png",
    imageUrl: "/images/spring-travel-campaign.png",
    category: "landing",
    year: 2026,
    tags: ["营销视觉", "产品精细渲染", "租售转化大促"],
    designBy: "王军震",
    themeColor: "#2b82f6",
    layout: "cyber",
    strategy: [
      "微缩春色拟物化结构：将摄影机与奢华配件置于天然年轮木墩和潺潺欢畅的溪流中，营造极富生机的春日出游故事感",
      "黄金分割出游色彩体系：提炼明朗的天空蓝、薄荷绿、暖阳橙作为辅助配色，奠定高活跃、踏春度假、温暖春日色调体系",
      "全链路多端延展提效：运用 3D 渲染器与 AI 图像提速工具相结合，在极短周期内自适应分发宽幅横幅、手机会场、以及品类优惠卡券等多态视觉模态"
    ],
    secondaryImages: [
      "/images/spring-travel-campaign.png",
      "/images/camera-gear-detail.png",
      "/images/spring-travel-campaign.png",
      "/images/camera-gear-detail.png",
    ]
  },
  {
    id: "11",
    title: "转转熊IP应用",
    subtitle: "AIGC生成运营视觉场景与活动",
    description: "AIGC生成运营视觉场景与活动",
    coverImage: "/src/assets/images/regenerated_image_1780327603434.jpg",
    imageUrl: "/src/assets/images/regenerated_image_1780327603434.jpg",
    category: "personal",
    year: 2026,
    tags: ["3D卡通IP", "潮玩手办设计", "LORA model validation", "视觉规范落地"],
    designBy: "王军震",
    themeColor: "#FF4D4F",
    layout: "dynamic",
    secondaryImages: [
      "/src/assets/images/regenerated_image_1780327603434.jpg",
      "/src/assets/images/regenerated_image_1780327610363.jpg",
      "/src/assets/images/regenerated_image_1780327607068.jpg",
      "/images/bear-cyber-3.png",
      "/src/assets/images/regenerated_image_1780327634662.jpg",
      "/src/assets/images/regenerated_image_1780328682494.png"
    ],
  },
  {
    id: "12",
    title: "618大促毕业季",
    subtitle: "AIGC GENERATED PROMOTION KV",
    description: "618大促加毕业季，打造专属大促氛围，结合 AI生成背景与交互设计",
    coverImage: "/images/618-graduation-campaign.jpg",
    imageUrl: "/images/618-graduation-campaign.jpg",
    category: "landing",
    year: 2025,
    tags: ["大促营销", "毕业季", "AIGC", "交互设计"],
    designBy: "王军震",
    themeColor: "#FF4D4F",
    layout: "dynamic",
    secondaryImages: [
      "/images/618-graduation-campaign.jpg",
      "/images/618-secondary1.jpg",
      "/images/618-secondary2.jpg"
    ]
  }
];

export const experiences = [
  {
    company: "转转",
    logo: "/images/zhuanzhuan-logo.png",
    role: "运营视觉设计师 | 转转平台设计",
    period: "2024年7月-至今",
    color: "#ff4d4f",
    details: [
      "【B2C业务】：平台大促视觉设计/日常活动设计",
      "【租赁业务】：日常营销活动设计",
      "【AI模型训练】：IP转转熊Lora模型训练",
    ],
  },
  {
    company: "滴滴",
    logo: "/images/didi-logo.png",
    role: "创意视觉实习生 | 网约车平台设计",
    period: "2023年10月-2024年4月",
    color: "#ff8800",
    details: [
      "【网约车乘客端APP】：节日的营销活动视觉设计和相关的延展设计。",
      "【网约车司机端APP】：司机端资源位的活动入口设计。",
      "【3D素材库搭建】：用于营销活动使用的相关3D元素库搭建。",
    ],
  },
];
